AWSTemplateFormatVersion: 2010-09-09
Description: This template instantiates an EC2 instance with Teradici installed and a prompt to install Adobe Premier Pro via Adobe Creative Cloud
Metadata:
  AWSAMIRegionMap:
    Filters:
      TERADICIWIN:
        name: graphics-agent-windows-2019-aws-market*
        owner-alias: aws-marketplace
        product-code.type: marketplace
        product-code: 4af6zv023dsu3c28day09b2a9
Parameters:
  FirstStation:
    Type: String
  WorkstationNumber:
    Type: String
  RootURL:
    Type: String
  pcoipRegistrationCode:
    Type: String
  domainName:
    Type: String
  adServiceAccountUsername:
    Type: String
  adServiceAccountPassword:
    Type: String
    NoEcho: "True"
  gfxworkstationSubnet:
    Type: String
  gfxworkstationSG:
    Type: String
  gfxworkstationKeyName:
    Type: String
  windowsGrxInstanceType:
    Type: String
  workstationAdminPassword:
    Type: String
    NoEcho: "True"
  pcoipAgentLocationUrl:
    Type: String
  pcoipAgentFilename:
    Type: String
  SMBShareName:
    Type: String
  FloatDNSName:
    Type: String
  DomainControllerSecretsName:
    Type: String

Conditions:
  FirstWS: !Equals
    - !Ref FirstStation
    - "TRUE"

Mappings:
  AWSAMIRegionMap:
    us-east-1:
      TERADICIWIN: ami-0299806a7a0db74d5
    us-east-2:
      TERADICIWIN: ami-0f095edee697b1ef3
    us-west-1:
      TERADICIWIN: ami-08281d8103b7f233f
    us-west-2:
      TERADICIWIN: ami-0f7adbd07e91f6e83 
    ap-south-1:
      TERADICIWIN: ami-0702d91f70d599eed
    ap-northeast-1:
      TERADICIWIN: ami-03ecf29831389b4b9
    ap-northeast-2:
      TERADICIWIN: ami-07b7cbeb34f3aec62
    ap-southeast-1:
      TERADICIWIN: ami-0c31c675576e68ef7
    ap-southeast-2:
      TERADICIWIN: ami-0d08f56894d871c29
    ca-central-1:
      TERADICIWIN: ami-0904994a77fe6564f
    eu-central-1:
      TERADICIWIN: ami-04ebd347ba3b42e14
    eu-west-1:
      TERADICIWIN: ami-06f1c5023ce0f9d81
    eu-west-2:
      TERADICIWIN: ami-08f26e8c09e56cd6e
    eu-west-3:
      TERADICIWIN: ami-0cca22c15cd254f37
    sa-east-1:
      TERADICIWIN: ami-07819057af66de0b6

Resources:

  WorkstationEIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  AssociateEIP:
    Type: "AWS::EC2::EIPAssociation"
    Properties:
      AllocationId: !GetAtt WorkstationEIP.AllocationId
      NetworkInterfaceId: !Ref WorkstationNI

  WorkstationNI:
    Type: "AWS::EC2::NetworkInterface"
    Properties:
      SubnetId: !Ref gfxworkstationSubnet
      GroupSet:
        -  !Ref gfxworkstationSG

  WorkstationAccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: WorkstationS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                Resource: !Join
                  - ""
                  - - "arn:aws:s3:::"
                    - !Select [0, !Split [".", !Select [1, !Split ["//", !Ref RootURL]]]]
                    - "*"
        - PolicyName: WorkstationSecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: "*"
  WorkstationAccessProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref WorkstationAccessRole

  windowsGfxWorkstation:
    Type: 'AWS::EC2::Instance'
    Metadata:
      "AWS::CloudFormation::Authentication":
        rolebased:
          buckets:
            - qumuloadobe
          roleName: !Ref WorkstationAccessRole
          type: S3

      "AWS::CloudFormation::Init":
        configSets:
          config:
            - "1-setup"
            - "2-run"
        "1-setup":
          files:
            "C:\\cfn\\cfn-hup.conf":
              authentication: rolebased
              context:
                Region: !Ref "AWS::Region"
                StackId: !Ref "AWS::StackId"
              source: !Join ["", [!Ref RootURL, "cfn-init/cfn-hup.conf"]]
            "C:\\cfn\\hooks.d\\cfn-auto-reloader.conf":
              authentication: rolebased
              context:
                Region: !Ref "AWS::Region"
                ResourceName: windowsGfxWorkstation
                StackId: !Ref "AWS::StackId"
              source: !Join ["", [!Ref RootURL, "cfn-init/cfn-auto-reloader.conf"]]
            "C:\\cfn\\install\\CleanupFiles.cmd":
              content: !Sub |
                del /f /q c:\cfn\\install\workstation.conf              
            "C:\\cfn\\install\\workstation.conf":
              authentication: rolebased
              context:
                pcoipAgentLocationUrl: !Ref pcoipAgentLocationUrl
                pcoipRegistrationCode: !Ref pcoipRegistrationCode
                workstationAdminPassword: !Ref workstationAdminPassword
                adServiceAccountPassword: !Ref adServiceAccountPassword
                domainName: !Ref domainName
                adServiceAccountUsername: !Ref adServiceAccountUsername
              source: !Join ["", [!Ref RootURL, "cfn-init/workstation.conf"]]
            "C:\\cfn\\install\\workstationsetup.ps1":
              authentication: rolebased
              source: !Join ["", [!Ref RootURL, "cfn-init/workstationsetup.ps1"]]
            "C:\\mapdrive.ps1":
              content: !Sub |
                New-PSDrive -Name Q -PSProvider FileSystem -Root "\\${FloatDNSName}\${SMBShareName}" -Scope Global -Persist
            "C:\\cfn\\install\\install-chrome.ps1":
              authentication: rolebased
              source: !Join ["", [!Ref RootURL, "cfn-init/install-chrome.ps1"]]
            "C:\\cfn\\install\\launch-adobe.ps1":
              content: !Sub |
                Start-Process -FilePath "C:\Program Files\Google\Chrome\Application\chrome.exe" -ArgumentList "https://creativecloud.adobe.com"
            "C:\\cfn\\install\\defender-exclude.ps1":
              authentication: rolebased
              source: !Join ["", [!Ref RootURL, "cfn-init/defender-exclude.ps1"]]
          services:
            windows:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - "c:\\cfn\\cfn-hup.conf"
                  - "c:\\cfn\\hooks.d\\cfn-auto-reloader.conf"
        "2-run":
          commands:
            "01-setup-workstation":
              command: "powershell.exe -ExecutionPolicy Unrestricted -File C:\\cfn\\install\\workstationsetup.ps1 -WorkstationConf c:\\cfn\\install\\workstation.conf"
              waitAfterCompletion: "forever"
            "02-configure-task-map-drive":
              command: !Join 
                - ""
                - - "schtasks /create /tn \"Map Q Drive\" /ru \""
                  - !Ref domainName
                  - "\\Domain Users\" /sc ONLOGON /tr \"powershell.exe -File c:\\mapdrive.ps1\""
              waitAfterCompletion: 0
            "03-install-chrome":
              command: "powershell.exe -ExecutionPolicy Unrestricted -File C:\\cfn\\install\\install-chrome.ps1"
              waitAfterCompletion: 10
            "04-configure-task-launch-adobe":
              command: !Join 
                - ""
                - - "schtasks /create /tn \"Launch Adobe Webpage\" /ru \""
                  - !Ref domainName
                  - "\\Domain Users\" /sc ONLOGON /tr \"powershell.exe -File c:\\cfn\\install\\launch-adobe.ps1\""
              waitAfterCompletion: 0
            "05-configure-task-defender-exclude":
              command: !Join 
                - ""
                - - "schtasks /create /tn \"Exclude Defender Q Drive\" /ru \""
                  - !Ref domainName
                  - "\\Domain Users\" /sc ONLOGON /tr \"powershell.exe -File C:\\cfn\\install\\defender-exclude.ps1 -DomainControllerSecrets "
                  - !Ref DomainControllerSecretsName
                  - " -DomainName "
                  - !Ref domainName
                  - "\" /rl HIGHEST"
            "06-cleanup-files":
              command: "C:\\cfn\\install\\CleanupFiles.cmd"
              waitAfterCompletion: 0

    Properties:
      ImageId: !FindInMap [AWSAMIRegionMap, !Ref "AWS::Region", TERADICIWIN]
      InstanceType: !Ref windowsGrxInstanceType
      Monitoring: false
      IamInstanceProfile: !Ref WorkstationAccessProfile
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref WorkstationNI
          DeviceIndex: 0
      KeyName: !Ref gfxworkstationKeyName
      Tags:
        - Key: Name
          Value: !If
            - FirstWS
            - !Sub "${AWS::StackName}- Windows Adobe Workstation #${WorkstationNumber}"
            - !Join
              - "-"
              - - !Select [0, !Split ["-", !Ref "AWS::StackName"]]
                - !Select [1, !Split ["-", !Ref "AWS::StackName"]]
                - !Select [2, !Split ["-", !Ref "AWS::StackName"]]
                - !Sub " Windows Adobe Workstation #${WorkstationNumber}"

      UserData:
        Fn::Base64: !Sub |
          <powershell>
          cfn-init.exe -v -c config --stack ${AWS::StackName} --resource windowsGfxWorkstation --region ${AWS::Region}
          cfn-signal.exe -e $lastexitcode --stack ${AWS::StackName} --resource windowsGfxWorkstation --region ${AWS::Region}
          </powershell>

  domainNameSSM: 
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-domainName"       
      Value: !Ref domainName
      Type: String

  gfxworkstationKeyNameSSM: 
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-gfxworkstationKeyName"       
      Value: !Ref gfxworkstationKeyName
      Type: String

  gfxworkstationSGSSM:
    Type: AWS::SSM::Parameter
    Condition: FirstWS 
    Properties:
      Name: !Sub "${AWS::StackName}-gfxworkstationSG"      
      Value: !Ref gfxworkstationSG
      Type: String

  gfxworkstationSubnetSSM:
    Type: AWS::SSM::Parameter
    Condition: FirstWS 
    Properties:
      Name: !Sub "${AWS::StackName}-gfxworkstationSubnet"     
      Value: !Ref gfxworkstationSubnet
      Type: String

  pcoipAgentFilenameSSM:
    Type: AWS::SSM::Parameter
    Condition: FirstWS 
    Properties:
      Name: !Sub "${AWS::StackName}-pcoipAgentFilename"     
      Value: !Ref pcoipAgentFilename
      Type: String

  pcoipAgentLocationUrlSSM: 
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-pcoipAgentLocationUrl"      
      Value: !Ref pcoipAgentLocationUrl
      Type: String

  pcoipRegistrationCodeSSM: 
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-pcoipRegistrationCode"       
      Value: !Ref pcoipRegistrationCode
      Type: String

  windowsGfxInstanceAMISSM: 
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-windowsGfxInstanceAMI"       
      Value: !FindInMap [AWSAMIRegionMap, !Ref "AWS::Region", TERADICIWIN]
      Type: String

  windowsGrxInstanceTypeSSM: 
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-windowsGrxInstanceType"        
      Value: !Ref windowsGrxInstanceType
      Type: String

  SMBShareNameSSM: 
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-SMBShareName"     
      Value: !Ref SMBShareName
      Type: String

  FloatDNSNameSSM:
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-FloatDNSName"        
      Value: !Ref FloatDNSName
      Type: String

  DomainControllerSecretsNameSSM: 
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-DomainControllerSecretsName"
      Value: !Ref DomainControllerSecretsName
      Type: String

  RootURLSSM: 
    Type: AWS::SSM::Parameter
    Condition: FirstWS
    Properties:
      Name: !Sub "${AWS::StackName}-RootURL"
      Value: !Ref RootURL
      Type: String

Outputs:
  GFXWorkstationHostname:
    Description: "The public dns hostname of the Workstation Instance"
    Value: !GetAtt windowsGfxWorkstation.PublicDnsName

  GFXWorkstationPublicIP:
    Description: "The Public IP Address of the Workstation Instance"
    Value: !GetAtt windowsGfxWorkstation.PublicIp

  GFXWorkstationNumber:
    Description: "Workstation Instance Number"
    Value: !Ref WorkstationNumber

  GFXWorkstationStackName:
    Description: The Name of this AWS Stack
    Value: !Ref "AWS::StackName"
    Condition: FirstWS



