AWSTemplateFormatVersion: "2010-09-09"
Description: This template instantiates an AWS Network Load Balancer connected to the Qumulo Cluster Static IP addresses, ensuring reachability

Parameters:
  VPCID:
    Type: String
  PublicSubnetID:
    Type: String
  NodeIPs:
    Type: String

Resources:
  NLBEIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  NLB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: !Join
        - ""
        - - "qumulo-mgmt-"
          - !Select [2, !Split ["-", !Ref "AWS::StackName"]]
      Type: network
      IpAddressType: ipv4
      Scheme: internet-facing
      SubnetMappings: 
        - AllocationId: !GetAtt
          - NLBEIP
          - AllocationId
          SubnetId: !Ref PublicSubnetID
#      Tags:
#        - Key: Name
#          Value: !Join
#            - ""
#            - - Ref: "AWS::StackName"
#              - " - Qumulo Management NLB"

  NLBTargetGroupMgmt:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: !Join
        - ""
        - - "cluster-target-"
          - !Select [2, !Split ["-", !Ref "AWS::StackName"]]
      TargetType: ip
      Protocol: TCP
      Port: 80
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: "true"
        - Key: stickiness.type
          Value: source_ip
      Targets:
        - Id: !Select [0, !Split [", ", !Ref NodeIPs]]
          Port: 443
        - Id: !Select [1, !Split [", ", !Ref NodeIPs]]
          Port: 443
        - Id: !Select [2, !Split [", ", !Ref NodeIPs]]
          Port: 443
        - Id: !Select [3, !Split [", ", !Ref NodeIPs]]
          Port: 443
      VpcId: !Ref VPCID

  NLBListenerHTTPS:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref NLBTargetGroupMgmt
      LoadBalancerArn: !Ref NLB
      Port: 443
      Protocol: TCP

Outputs:
  ManagementEIP:
    Value: !Join
      - ""
      - - "https://"
        - !Ref NLBEIP