AWSTemplateFormatVersion: "2010-09-09"
Description: This template stores Secrets for subsequent use in nested stacks (qs-1s0p493kd)

Parameters:
  SideCarUsername:
    Type: String
  SideCarPassword:
    Type: String
    NoEcho: "True"
  adServiceAccountUsername:
    Type: String
  adServiceAccountPassword:
    Type: String
    NoEcho: "True"
  dcAdminUsername:
    Type: String
  dcAdminPassword:
    Type: String
    NoEcho: "True"    
  safeModeAdminPassword:
    Type: String
    NoEcho: "True"
  testusername:
    Type: String
  testuserpassword:
    Type: String
    NoEcho: "True"

Resources:
  SideCarSecrets:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub "${AWS::StackName}-SideCarSecrets"
      Description: "Sidecar Lambda function user name and password for Qumulo cluster access"
      SecretString: !Sub '{ "username" : "${SideCarUsername}", "password" : "${SideCarPassword}" }'
      
  DomainControllerSecrets:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub "${AWS::StackName}-DomainControllerSecrets"
      Description: "Domain Controller user names and passwords"
      SecretString: !Sub '{ "adServiceAccountUsername" : "${adServiceAccountUsername}", "adServiceAccountPassword" : "${adServiceAccountPassword}",
                            "testUsername" : "${testusername}", "testUserPassword" : "${testuserpassword}", 
                            "dcAdminUsername" : "${dcAdminUsername}", "dcAdminPassword" : "${dcAdminPassword}",
                            "safeModeAdminPassword" : "${safeModeAdminPassword}" }'

Outputs:
  SideCarSecretsArn:
    Value: !Ref SideCarSecrets
  DomainControllerSecretsArn:
    Value: !Ref DomainControllerSecrets
  DomainControllerSecretsName:
    Value: !Sub "${AWS::StackName}-DomainControllerSecrets"
